[build] 
  publish = "dist"
  command = ""

[dev] 
  publish = "dist"
  command = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/news/*"
  to = "/.netlify/functions/odb-view-item/:splat"
  status = 200
